name: Deploy Lambda and Layers

on:
  push:
    branches:
      - main
    paths:
      - 'layers/**'
      - 'terraform/**'
      - 'src/**'
      - 'makefile'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Lambda and Layers
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Authenticate with AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Install Prerequisites
      - name: Install Prerequisites
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          pip install --upgrade pip
          pip install -r layers/requirements.txt

      # Run Makefile Commands
      - name: Run Makefile Tasks
        run: |
          make create-bucket
          make build-layer

      # Initialize Terraform
      - name: Initialize Terraform
        run: make terraform-init

      # Validate Terraform Configuration
      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      # Apply Terraform Changes
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
